// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<WalletCreationDetails> createWallet() =>
    RustLib.instance.api.crateApiWalletCreateWallet();

Future<WalletCreationDetails> restoreWallet({
  required List<String> seedWords,
  String? passphrase,
}) => RustLib.instance.api.crateApiWalletRestoreWallet(
  seedWords: seedWords,
  passphrase: passphrase,
);

class WalletCreationDetails {
  final String tariAddress;
  final int walletBirthday;
  final String spendPublicKeyHex;
  final String viewPrivateKeyHex;

  const WalletCreationDetails({
    required this.tariAddress,
    required this.walletBirthday,
    required this.spendPublicKeyHex,
    required this.viewPrivateKeyHex,
  });

  @override
  int get hashCode =>
      tariAddress.hashCode ^
      walletBirthday.hashCode ^
      spendPublicKeyHex.hashCode ^
      viewPrivateKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCreationDetails &&
          runtimeType == other.runtimeType &&
          tariAddress == other.tariAddress &&
          walletBirthday == other.walletBirthday &&
          spendPublicKeyHex == other.spendPublicKeyHex &&
          viewPrivateKeyHex == other.viewPrivateKeyHex;
}
